### ISSUE TITLE
If I multiply the CTC loss by a factor, that has no effect on the gradients of probs

### ISSUE THREAD

**Issue by weedwind** [SeanNaren/warp-ctc#69] opened 2018-07-12 18:11 UTC
Hi,

When I ran the example code in the readme of this repo, I added one line:

cost = 0.1 * cost

Then, I printed out the grad of the probs variable, and compare it with the original code where there is no scaling. But the grads are exactly the same. So why the scaling has no effect?

I did another example with MSELoss that pytorch provided. The scaling did scale the grad there.

I am asking this question because I want to build a weighted sum of ctc loss and some other loss, so the weight needs to be effective for ctc.

My pytorch version is 0.3.1, and ctc was installed from the older repo.

Thank you very much for help.

**Comment by SeanNaren** [comment] 2018-07-13 07:49
Duplicate of [this](https://github.com/SeanNaren/deepspeech.pytorch/issues/250). I'm going to address the issue there @weedwind!

**Closed as completed by SeanNaren** 2018-07-13 07:49 UTC
